### PR TITLE
Minor Improvement

### PR DESCRIPTION
**Pull request by MohammadSianaki**

### CODE REVIEW

**Comment by iammert** [comment]
Thanks for your PR. Can you please resolve your conflicts.

**Comment by MohammadSianaki** [comment]
> Thanks for your PR. Can you please resolve your conflicts.

:ballot_box_with_check:  Conflicts resolved

**Comment by iammert** [comment]
Thanks for your support @MohammadSianaki. I just want to ask a simple question. Is there any reason to change enum classes to sealed class. I know the power of the sealed classes in some cases. But I think `CryptoType` enum class doesn't have to be a sealed class in my opinion. 

I would love to see a document, blog post or anything about this. Thanks. 🙌

**Comment by MohammadSianaki** [comment]
>  I think `CryptoType` enum class doesn't have to be a sealed class in my opinion.

Yeah, I guess you're right:+1: 
 enums should just be right for `CryptoType`

Please, give your opinion about the other changes which I made. Thanks

**Pull request closed without merging**
